### ISSUE TITLE
Error with Pytorch 1.7.1 + CUDA11.0

### ISSUE THREAD

**Issue by zhoujuncc1** [zhoujuncc1/shenjingcat#4]
Traceback (most recent call last):
  File "examples/cifar10/cifar10.py", line 12, in <module>
    from catSNN import spikeLayer, transfer_model, load_model, max_weight, normalize_weight, SpikeDataset ,fuse_bn_recursively, fuse_module
  File "/home/zhoujun/virtual_envs/snn-new/lib/python3.6/site-packages/catSNN-0.0.0-py3.6.egg/catSNN/__init__.py", line 1, in <module>
  File "/home/zhoujun/virtual_envs/snn-new/lib/python3.6/site-packages/catSNN-0.0.0-py3.6.egg/catSNN/cat.py", line 7, in <module>
ImportError: /home/zhoujun/virtual_envs/snn-new/lib/python3.6/site-packages/catCuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

**Comment by zhangluyan9** [comment]
export PATH=/user/local/cuda-11.0/bin:/$PATH
works for me. Should recompile if you change the PyTorch version.

**Comment by zhoujuncc1** [comment]
If above is not work, you also need to set your $CUDA_HOME to the correct cuda directory.
